// web/src/components/AsyncState.tsx
import { useEffect, useRef, useState } from 'react'
import { useI18n } from '../i18n'

export function useAsync<T>(loader: () => Promise<T>, deps: unknown[] = []) {
  const [data, setData] = useState<T | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const loaderRef = useRef(loader)
  loaderRef.current = loader

  useEffect(() => {
    let active = true
    setLoading(true)
    setError(null)
    loaderRef.current()
      .then((result) => {
        if (active) setData(result)
      })
      .catch((err: Error) => {
        if (active) setError(err.message)
      })
      .finally(() => {
        if (active) setLoading(false)
      })
    return () => {
      active = false
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, deps)

  return {
    data,
    error,
    loading,
    reload: () => loaderRef.current().then(setData).catch((e: Error) => setError(e.message)),
  }
}

export function AsyncState<T>({
  loading,
  error,
  data,
  emptyText,
  refreshing = false,
  children,
}: {
  loading: boolean
  error: string | null
  data: T | null | undefined
  emptyText?: string
  refreshing?: boolean
  children: (data: T) => React.ReactNode
}) {
  const { t } = useI18n()
  const resolvedEmpty = emptyText ?? t('app.empty')

  if (loading && data == null) return <div className="loading">{t('app.loading')}</div>
  if (error && data == null) return <div className="error">{error}</div>
  if (data == null || (Array.isArray(data) && data.length === 0)) {
    return <div className="empty">{resolvedEmpty}</div>
  }

  return (
    <>
      {refreshing && <div className="silent-refresh-bar" aria-hidden="true" />}
      {children(data)}
    </>
  )
}

// control-plane-web/src/app/shared/async-state.component.ts
import { Component, ContentChild, Input, TemplateRef } from '@angular/core'
import { I18nService } from '../core/i18n.service'

@Component({
  selector: 'app-async-state',
  template: `
    <div class="loading" *ngIf="loading && isMissing">{{ i18n.t('app.loading') }}</div>
    <div class="error" *ngIf="error && isMissing">{{ error }}</div>
    <div class="empty" *ngIf="!loading && !error && isEmpty">{{ emptyText || i18n.t('app.empty') }}</div>
    <ng-container *ngIf="showContent">
      <div class="silent-refresh-bar" *ngIf="refreshing" aria-hidden="true"></div>
      <ng-container *ngTemplateOutlet="content; context: { $implicit: data }"></ng-container>
    </ng-container>
  `,
})
export class AsyncStateComponent {
  @Input() loading = false
  @Input() error: string | null = null
  @Input() data: unknown
  @Input() emptyText?: string
  @Input() refreshing = false
  @ContentChild(TemplateRef) content!: TemplateRef<{ $implicit: unknown }>

  constructor(public i18n: I18nService) {}

  get isMissing() {
    return this.data == null
  }

  get isEmpty() {
    return this.data == null || (Array.isArray(this.data) && this.data.length === 0)
  }

  get showContent() {
    return this.data != null && !(Array.isArray(this.data) && this.data.length === 0)
  }
}
