// web/src/components/CronEditor.tsx
import { useMemo } from 'react'
import type { CronEditorConfig, CronPreset } from '../utils/cron'
import {
  CRON_PRESET_OPTIONS,
  buildCronExpression,
  defaultCronConfig,
  describeCronExpression,
  listTimezones,
  weekdayLabel,
} from '../utils/cron'
import { useI18n } from '../i18n'

interface Props {
  config: CronEditorConfig
  timezone: string
  onConfigChange: (config: CronEditorConfig) => void
  onTimezoneChange: (timezone: string) => void
}

export function CronEditor({ config, timezone, onConfigChange, onTimezoneChange }: Props) {
  const { t } = useI18n()
  const timezones = useMemo(() => listTimezones(timezone), [timezone])

  const setPreset = (preset: CronPreset) => {
    onConfigChange({ ...defaultCronConfig(), ...config, preset })
  }

  const update = (patch: Partial<CronEditorConfig>) => {
    onConfigChange({ ...config, ...patch })
  }

  const toggleWeekday = (day: number) => {
    const current = config.daysOfWeek || []
    const next = current.includes(day) ? current.filter((d) => d !== day) : [...current, day]
    update({ daysOfWeek: next.sort((a, b) => a - b) })
  }

  let preview = describeCronExpression(config, timezone, t)
  let cronExpr = ''
  try {
    cronExpr = buildCronExpression(config, t)
  } catch (error) {
    preview = String(error)
  }

  return (
    <div className="form-grid">
      <div className="form-row">
        <label>{t('schedule.frequency')}</label>
        <div className="cron-preset-grid">
          {CRON_PRESET_OPTIONS.map((option) => (
            <button
              key={option.value}
              type="button"
              className={`cron-preset-card${config.preset === option.value ? ' active' : ''}`}
              onClick={() => setPreset(option.value)}
            >
              <div className="cron-preset-title">{t(option.labelKey)}</div>
              <div className="cron-preset-hint">{t(option.hintKey)}</div>
            </button>
          ))}
        </div>
      </div>

      {config.preset === 'hourly' && (
        <div className="form-row">
          <label htmlFor="cronMinute">{t('schedule.minuteOfHour')}</label>
          <input
            id="cronMinute"
            type="number"
            min={0}
            max={59}
            value={config.minute ?? 0}
            onChange={(e) => update({ minute: Number(e.target.value) })}
          />
        </div>
      )}

      {(config.preset === 'daily' || config.preset === 'weekly' || config.preset === 'monthly') && (
        <div className="form-row cron-time-row">
          <div>
            <label htmlFor="cronHour">{t('schedule.hour')}</label>
            <input
              id="cronHour"
              type="number"
              min={0}
              max={23}
              value={config.hour ?? 9}
              onChange={(e) => update({ hour: Number(e.target.value) })}
            />
          </div>
          <div>
            <label htmlFor="cronMinuteOfHour">{t('schedule.minute')}</label>
            <input
              id="cronMinuteOfHour"
              type="number"
              min={0}
              max={59}
              value={config.minuteOfHour ?? 0}
              onChange={(e) => update({ minuteOfHour: Number(e.target.value) })}
            />
          </div>
        </div>
      )}

      {config.preset === 'weekly' && (
        <div className="form-row">
          <label>{t('schedule.weekdays')}</label>
          <div className="cron-weekday-grid">
            {[0, 1, 2, 3, 4, 5, 6].map((day) => (
              <label key={day} className={`cron-weekday${config.daysOfWeek?.includes(day) ? ' active' : ''}`}>
                <input
                  type="checkbox"
                  checked={config.daysOfWeek?.includes(day) || false}
                  onChange={() => toggleWeekday(day)}
                />
                {weekdayLabel(day, t)}
              </label>
            ))}
          </div>
        </div>
      )}

      {config.preset === 'monthly' && (
        <div className="form-row">
          <label htmlFor="cronDayOfMonth">{t('schedule.dayOfMonth')}</label>
          <input
            id="cronDayOfMonth"
            type="number"
            min={1}
            max={31}
            value={config.dayOfMonth ?? 1}
            onChange={(e) => update({ dayOfMonth: Number(e.target.value) })}
          />
        </div>
      )}

      {config.preset === 'custom' && (
        <div className="form-row">
          <label htmlFor="cronCustom">{t('schedule.cronExpr')}</label>
          <input
            id="cronCustom"
            className="mono"
            value={config.customExpr || ''}
            onChange={(e) => update({ customExpr: e.target.value })}
            placeholder="0 9 * * 1-5"
          />
          <div className="cron-help">{t('schedule.cronHelp')}</div>
        </div>
      )}

      <div className="form-row">
        <label htmlFor="cronTimezone">{t('schedule.timezone')}</label>
        <select id="cronTimezone" value={timezone} onChange={(e) => onTimezoneChange(e.target.value)}>
          {timezones.map((tz) => (
            <option key={tz} value={tz}>{tz}</option>
          ))}
        </select>
      </div>

      <div className="cron-preview">
        <div className="cron-preview-title">{t('schedule.preview')}</div>
        <div>{preview}</div>
        {cronExpr && <div className="mono cron-preview-expr">{t('schedule.expr', { expr: cronExpr })}</div>}
      </div>
    </div>
  )
}

// control-plane-web/src/app/shared/cron-editor.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core'
import { I18nService } from '../core/i18n.service'
import type { CronEditorConfig, CronPreset } from '../utils/cron'
import {
  CRON_PRESET_OPTIONS,
  buildCronExpression,
  defaultCronConfig,
  describeCronExpression,
  listTimezones,
  weekdayLabel,
} from '../utils/cron'

@Component({
  selector: 'app-cron-editor',
  template: `
    <div class="form-grid">
      <div class="form-row">
        <label>{{ i18n.t('schedule.frequency') }}</label>
        <div class="cron-preset-grid">
          <button
            *ngFor="let option of presets"
            type="button"
            class="cron-preset-card"
            [class.active]="config.preset === option.value"
            (click)="setPreset(option.value)"
          >
            <div class="cron-preset-title">{{ i18n.t(option.labelKey) }}</div>
            <div class="cron-preset-hint">{{ i18n.t(option.hintKey) }}</div>
          </button>
        </div>
      </div>

      <div class="form-row" *ngIf="config.preset === 'hourly'">
        <label for="cronMinute">{{ i18n.t('schedule.minuteOfHour') }}</label>
        <input id="cronMinute" type="number" min="0" max="59" [ngModel]="config.minute ?? 0" (ngModelChange)="update({ minute: +$event })" />
      </div>

      <div class="form-row cron-time-row" *ngIf="config.preset === 'daily' || config.preset === 'weekly' || config.preset === 'monthly'">
        <div>
          <label for="cronHour">{{ i18n.t('schedule.hour') }}</label>
          <input id="cronHour" type="number" min="0" max="23" [ngModel]="config.hour ?? 9" (ngModelChange)="update({ hour: +$event })" />
        </div>
        <div>
          <label for="cronMinuteOfHour">{{ i18n.t('schedule.minute') }}</label>
          <input id="cronMinuteOfHour" type="number" min="0" max="59" [ngModel]="config.minuteOfHour ?? 0" (ngModelChange)="update({ minuteOfHour: +$event })" />
        </div>
      </div>

      <div class="form-row" *ngIf="config.preset === 'weekly'">
        <label>{{ i18n.t('schedule.weekdays') }}</label>
        <div class="cron-weekday-grid">
          <label *ngFor="let day of weekdays" class="cron-weekday" [class.active]="hasWeekday(day)">
            <input type="checkbox" [checked]="hasWeekday(day)" (change)="toggleWeekday(day)" />
            {{ weekdayLabel(day, i18n.t) }}
          </label>
        </div>
      </div>

      <div class="form-row" *ngIf="config.preset === 'monthly'">
        <label for="cronDayOfMonth">{{ i18n.t('schedule.dayOfMonth') }}</label>
        <input id="cronDayOfMonth" type="number" min="1" max="31" [ngModel]="config.dayOfMonth ?? 1" (ngModelChange)="update({ dayOfMonth: +$event })" />
      </div>

      <div class="form-row" *ngIf="config.preset === 'custom'">
        <label for="cronCustom">{{ i18n.t('schedule.cronExpr') }}</label>
        <input id="cronCustom" class="mono" [ngModel]="config.customExpr || ''" (ngModelChange)="update({ customExpr: $event })" placeholder="0 9 * * 1-5" />
        <div class="cron-help">{{ i18n.t('schedule.cronHelp') }}</div>
      </div>

      <div class="form-row">
        <label for="cronTimezone">{{ i18n.t('schedule.timezone') }}</label>
        <select id="cronTimezone" [ngModel]="timezone" (ngModelChange)="timezoneChange.emit($event)">
          <option *ngFor="let tz of timezones" [ngValue]="tz">{{ tz }}</option>
        </select>
      </div>

      <div class="cron-preview">
        <div class="cron-preview-title">{{ i18n.t('schedule.preview') }}</div>
        <div>{{ preview }}</div>
        <div class="mono cron-preview-expr" *ngIf="cronExpr">{{ i18n.t('schedule.expr', { expr: cronExpr }) }}</div>
      </div>
    </div>
  `,
})
export class CronEditorComponent {
  @Input() config: CronEditorConfig = defaultCronConfig()
  @Input() timezone = 'Asia/Shanghai'
  @Output() configChange = new EventEmitter<CronEditorConfig>()
  @Output() timezoneChange = new EventEmitter<string>()

  presets = CRON_PRESET_OPTIONS
  weekdays = [0, 1, 2, 3, 4, 5, 6]
  weekdayLabel = weekdayLabel

  constructor(public i18n: I18nService) {}

  get timezones() {
    return listTimezones(this.timezone)
  }

  get preview() {
    try {
      return describeCronExpression(this.config, this.timezone, this.i18n.t)
    } catch (error) {
      return String(error)
    }
  }

  get cronExpr() {
    try {
      return buildCronExpression(this.config, this.i18n.t)
    } catch {
      return ''
    }
  }

  setPreset(preset: CronPreset) {
    this.configChange.emit({ ...defaultCronConfig(), ...this.config, preset })
  }

  update(patch: Partial<CronEditorConfig>) {
    this.configChange.emit({ ...this.config, ...patch })
  }

  hasWeekday(day: number) {
    return this.config.daysOfWeek?.includes(day) || false
  }

  toggleWeekday(day: number) {
    const current = this.config.daysOfWeek || []
    const next = current.includes(day) ? current.filter((d) => d !== day) : [...current, day]
    this.update({ daysOfWeek: next.sort((a, b) => a - b) })
  }
}
