// web/src/components/JobTable.tsx
import { Link } from 'react-router-dom'
import type { JobSummary } from '../types/api'
import { formatTimestamp, getMetricReadWrite } from '../utils/format'
import { useI18n } from '../i18n'
import { StatusBadge } from './StatusBadge'

export function JobTable({
  jobs,
  showActions = false,
  selectable = false,
  selectedIds = [],
  onToggle,
  onToggleAll,
  onStop,
}: {
  jobs: JobSummary[]
  showActions?: boolean
  selectable?: boolean
  selectedIds?: string[]
  onToggle?: (jobId: string, checked: boolean) => void
  onToggleAll?: (checked: boolean) => void
  onStop?: (jobId: string) => void
}) {
  const { t } = useI18n()
  const rows = Array.isArray(jobs) ? jobs : []

  return (
    <div className="table-wrap">
      <table className="data-table">
        <thead>
          <tr>
            {selectable && <th className="select-column"><input aria-label={t('jobs.selectAll')} type="checkbox" checked={rows.length > 0 && rows.every((job) => selectedIds.includes(job.jobId))} onChange={(event) => onToggleAll?.(event.target.checked)} /></th>}
            <th>{t('jobs.colId')}</th>
            <th>{t('jobs.colName')}</th>
            <th>{t('jobs.colStatus')}</th>
            <th>{t('jobs.colCreated')}</th>
            <th>{t('jobs.colIO')}</th>
            {showActions && <th>{t('app.actions')}</th>}
          </tr>
        </thead>
        <tbody>
          {rows.map((job) => {
            const { read, write } = getMetricReadWrite(job.metrics as Record<string, unknown> | string | undefined)
            const checked = selectedIds.includes(job.jobId)
            return (
              <tr key={job.jobId}>
                {selectable && (
                  <td>
                    <input
                      type="checkbox"
                      checked={checked}
                      onChange={(e) => onToggle?.(job.jobId, e.target.checked)}
                    />
                  </td>
                )}
                <td className="mono">
                  <Link to={`/jobs/${job.jobId}`}>{job.jobId}</Link>
                </td>
                <td>{job.jobName || '—'}</td>
                <td><StatusBadge status={job.jobStatus} /></td>
                <td>{formatTimestamp(job.createTime)}</td>
                <td className="mono">{read} / {write}</td>
                {showActions && (
                  <td>
                    <button className="btn danger compact" type="button" onClick={() => onStop?.(job.jobId)}>
                      {t('jobs.stop')}
                    </button>
                  </td>
                )}
              </tr>
            )
          })}
        </tbody>
      </table>
    </div>
  )
}

// control-plane-web/src/app/shared/job-table.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core'
import { I18nService } from '../core/i18n.service'
import type { JobSummary } from '../types/api'
import { formatTimestamp, getMetricReadWrite } from '../utils/format'

@Component({
  selector: 'app-job-table',
  template: `
    <div class="table-wrap">
      <table class="data-table">
        <thead>
          <tr>
            <th class="select-column" *ngIf="selectable">
              <input
                [attr.aria-label]="i18n.t('jobs.selectAll')"
                type="checkbox"
                [checked]="allSelected"
                (change)="toggleAll.emit($any($event.target).checked)"
              />
            </th>
            <th>{{ i18n.t('jobs.colId') }}</th>
            <th>{{ i18n.t('jobs.colName') }}</th>
            <th>{{ i18n.t('jobs.colStatus') }}</th>
            <th>{{ i18n.t('jobs.colCreated') }}</th>
            <th>{{ i18n.t('jobs.colIO') }}</th>
            <th *ngIf="showActions">{{ i18n.t('app.actions') }}</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let job of rows">
            <td *ngIf="selectable">
              <input
                type="checkbox"
                [checked]="selectedIds.includes(job.jobId)"
                (change)="toggle.emit({ jobId: job.jobId, checked: $any($event.target).checked })"
              />
            </td>
            <td class="mono"><a [routerLink]="['/jobs', job.jobId]">{{ job.jobId }}</a></td>
            <td>{{ job.jobName || '—' }}</td>
            <td><app-status-badge [status]="job.jobStatus"></app-status-badge></td>
            <td>{{ formatTimestamp(job.createTime) }}</td>
            <td class="mono">{{ io(job).read }} / {{ io(job).write }}</td>
            <td *ngIf="showActions">
              <button class="btn danger compact" type="button" (click)="stop.emit(job.jobId)">
                {{ i18n.t('jobs.stop') }}
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  `,
})
export class JobTableComponent {
  @Input() jobs: JobSummary[] = []
  @Input() showActions = false
  @Input() selectable = false
  @Input() selectedIds: string[] = []
  @Output() toggle = new EventEmitter<{ jobId: string; checked: boolean }>()
  @Output() toggleAll = new EventEmitter<boolean>()
  @Output() stop = new EventEmitter<string>()

  formatTimestamp = formatTimestamp

  constructor(public i18n: I18nService) {}

  get rows() {
    return Array.isArray(this.jobs) ? this.jobs : []
  }

  get allSelected() {
    return this.rows.length > 0 && this.rows.every((job) => this.selectedIds.includes(job.jobId))
  }

  io(job: JobSummary) {
    return getMetricReadWrite(job.metrics as Record<string, unknown> | string | undefined)
  }
}
